[character]
success_symbol = "[ â¯](bold blue) "
error_symbol = "[ âœ—](bold red) "

[git_branch]
symbol = "î—½ "
truncation_length = 4
truncation_symbol = ""


[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
up_to_date = "âœ“"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ï¥”"
deleted = "ğŸ—‘"

[golang]
format = "via [ ï³‘ $version](bold cyan) "

[python]
symbol = "îœ¼ "
pyenv_version_name = true

[nodejs]
format = "via [ğŸ¤– $version](bold green) "

[java]
symbol = "î‰– "

[username]
style_user = "red bold"
style_root = "black bold"
format = " [ïˆ› $user]($style) "
disabled = false
show_always = true

[rust]
format = "via [î¨ $version ](red bold)"

[[battery.display]]  # "bold red" style and discharging_symbol when capacity is between 0% and 10%
threshold = 30
style = "bold red"

[[battery.display]]  # "bold yellow" style and ğŸ’¦ symbol when capacity is between 10% and 30%
threshold = 40
style = "bold yellow"
